// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC02f7KIn0d2uLRncZJDraQK7WGG226lFo',
    appId: '1:1057768975051:android:3b7b053faeb90abbfec94e',
    messagingSenderId: '1057768975051',
    projectId: 'yorumpusulas',
    storageBucket: 'yorumpusulas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBCbJQCrNGI74AW4VlIx3yHU1wEtmWolk',
    appId: '1:1057768975051:ios:9212d5485fb6f9c6fec94e',
    messagingSenderId: '1057768975051',
    projectId: 'yorumpusulas',
    storageBucket: 'yorumpusulas.firebasestorage.app',
    iosBundleId: 'com.yorumpusulas.yorumPusulas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_XQV3U_HV25k-CYml3w2GyvXKJutb0Y8',
    appId: '1:1057768975051:web:a8f3a15ec56a7b1efec94e',
    messagingSenderId: '1057768975051',
    projectId: 'yorumpusulas',
    authDomain: 'yorumpusulas.firebaseapp.com',
    storageBucket: 'yorumpusulas.firebasestorage.app',
    measurementId: 'G-0KB677ZZV2',
  );
}
